-- 로그인 SQL

SELECT MEMBER_NO , MEMBER_ID , MEMBER_NM , MEMBER_GENDER ,
TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일" HH24:MI:SS') ENROLL_DATE 
FROM "MEMBER"
WHERE MEMBER_ID = 'user01' -- ?
AND MEMBER_PW = 'pass01' -- ?
AND SECESSION_FL = 'N';


-- 아이디 중복검사

SELECT COUNT(*) 
FROM "MEMBER"
WHERE MEMBER_ID = 'user01' --?
AND SECESSION_FL = 'N';


-- 회원가입 SQL

INSERT INTO "MEMBER" 
VALUES(SEQ_MEMBER_NO.NEXTVAL, ?, ?, ?, ?, DEFAULT, DEFAULT)

-- 내 정보 조회 DAO XX
SELECT MEMBER_NO, MEMBER_ID , MEMBER_PW , MEMBER_NM , MEMBER_GENDER , ENROLL_DATE 
FROM "MEMBER" 
WHERE MEMBER_NO = 1
AND SECESSION_FL = 'N'

-- 전체 사원 정보 조회
SELECT MEMBER_ID , MEMBER_NM , MEMBER_GENDER 
FROM "MEMBER" 

-- 내 정보 수정 (이름, 성별)
UPDATE MEMBER 
SET MEMBER_NM = ?,
MEMBER_GENDER = ?
WHERE MEMBER_NO = ?

SELECT *
FROM "MEMBER";

ROLLBACK;


-- 비밀번호 변경
UPDATE "MEMBER" 
SET MEMBER_PW = ?
WHERE MEMBER_NO = ?

-- 비밀번호 조회
SELECT MEMBER_PW
FROM "MEMBER"
WHERE EMP_NO = ?


-- 회원 탈퇴
UPDATE "MEMBER" 
SET SECESSION_FL = 'Y'
WHERE MEMBER_NO = ?


--   1. 게시글 목록 조회(작성일 내림차순) --> 빡쎌듯
-- 	  (게시글 번호, 제목[댓글 수], 작성자명, 작성일, 조회수 )

SELECT BOARD_NO, BOARD_TITLE, 
	NVL(COUNT(COMMENT_NO),0) AS COUNT_COMMENT, 
	MEMBER_NM,
	TO_CHAR(b.CREATE_DT, 'YYYY"년" MM"월" DD"일" HH24:MI:SS') AS CREATE_DT,
	READ_COUNT   
FROM BOARD b 
JOIN "MEMBER" m USING(MEMBER_NO)
FULL JOIN "COMMENT" c USING(BOARD_NO)
WHERE b.DELETE_FL = 'N'
GROUP BY BOARD_NO, BOARD_TITLE, MEMBER_NM, TO_CHAR(b.CREATE_DT, 'YYYY"년" MM"월" DD"일" HH24:MI:SS'), READ_COUNT 
ORDER BY CREATE_DT ;



SELECT BOARD_NO , BOARD_TITLE , MEMBER_NM, READ_COUNT,
CASE 
	WHEN SYSDATE - CREATE_DT < 1/24/60
	THEN FLOOR((SYSDATE - CREATE_DT) * 24 * 60 * 60) || '초 전'
	WHEN SYSDATE - CREATE_DT < 1/24
	THEN FLOOR((SYSDATE-CREATE_DT) * 24 * 60) || '분 전'
	WHEN SYSDATE - CREATE_DT < 1
	THEN FLOOR((SYSDATE-CREATE_DT) * 24) || '초 전'
	ELSE TO_CHAR(CREATE_DT, 'YYYY-MM-DD')
END CREATE_DT,
(SELECT	count(*)
FROM "COMMENT" c
WHERE c.BOARD_NO = b.BOARD_NO ) COUNT_COMMENT
FROM BOARD b 
JOIN "MEMBER" m USING(MEMBER_NO)
WHERE b.DELETE_FL = 'N'
ORDER BY BOARD_NO DESC;




--	 * 2. 게시글 상세 조회(게시글 번호 입력 받음)
--	 *    (게시글 번호, 제목, 내용, 작성자명, 작성일, 조회수, 
--	 *     댓글 목록(작성일 오름차순 )

SELECT BOARD_NO , BOARD_TITLE , BOARD_CONTENT , MEMBER_NM, TO_CHAR(CREATE_DT, 'YYYY"년" MM"월" DD"일" HH24:MI:SS') AS CREATE_DT , READ_COUNT 
FROM BOARD b 
JOIN "MEMBER" m USING(MEMBER_NO)
WHERE BOARD_NO = 2 ;



--해당 게시글의 댓글 

SELECT BOARD_NO , COMMENT_NO , COMMENT_CONTENT , TO_CHAR(c.CREATE_DT, 'YYYY"년" MM"월" DD"일" HH24:MI:SS') AS "CREATE_DT" , MEMBER_NM
FROM "COMMENT" c 
JOIN "MEMBER" m USING(MEMBER_NO)
FULL JOIN BOARD b USING(BOARD_NO)
WHERE BOARD_NO = 1
AND c.DELETE_FL = 'N'
ORDER BY c.CREATE_DT ;

-- 게시글 작성

INSERT INTO BOARD 
VALUES (SEQ_BOARD_NO.NEXTVAL, ?, ?, DEFAULT, DEFAULT, DEFAULT, ?);


-- 게시판 번호 생성
SELECT SEQ_BOARD_NO.NEXTVAL FROM DUAL



SELECT COMMENT_NO, COMMENT_CONTENT,
				MEMBER_NO, MEMBER_NM,
				TO_CHAR(CREATE_DT, 'YYYY-MM-DD HH24:MI:SS') CREATE_DT
		FROM "COMMENT"
		JOIN MEMBER USING(MEMBER_NO)
		WHERE DELETE_FL = 'N'
		AND BOARD_NO = 1
		ORDER BY COMMENT_NO

